config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }
  root to: 'instruments#index'
  resources :instruments

  resources :sales, only: ['index', 'update', 'destroy'], path: "user/sales/"
  #get 'users/cart', to: 'order_items#index', as: :cart
  get 'user/cart/checkout', to: 'orders#checkout', as: :checkout

  patch 'user/cart/checkout', to: 'orders#create'

  get 'user/cart/history', to: 'orders#index', as: :history


  resources :order_items, path: "users/cart/"

  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  enum status: {active: 'active', in_cart: 'in cart', waiting: 'waiting', sold_out: 'sold out'}

  belongs_to :user, optional: true
  has_one_attached :image
  has_one :order_item, dependent: :destroy

  validates :brand, :model, :condition, :price, presence: true
  validates :description, length: {maximum: 500, too_long: "Too long!"}
  validates :price, length: {maximum: 7}

  BRAND = ["Fender", "Gibson", "Jackson", "Taylor", "Yamaha"]
  FINISH = ["Black", "White", "Yelow", "Red", "Navi", "Clear", "Satin"]
  CONDITION = ["New", "Excelent", "Used", "Poor"]


end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {empty: 'empty', cart: 'cart', open: 'open', canceled: "canceled"}
  has_many :order_items
  belongs_to :user

  after_update :change_items_status, if: Proc.new { |order| order.open?}

  private
  def change_items_status
    self.order_items.each do |o|
      o.instrument.update_attributes(status: "waiting")
    end

  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :instrument
  belongs_to :order

  after_create do
    if self.order.empty?
      self.order.cart!
    end
  end


  after_destroy do
    self.instrument.active!
    if OrderItem.where(order_id: self.order_id).empty?
      self.order.empty!
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :instruments
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
load 'current_cart'
class ApplicationController < ActionController::Base
  include SetCart
  helper_method :current_cart
end

app/controllers/current_cart.rb
class CurrentCart

  def nil_session
    session[:cart_token] = nil
  end

  def initialize(token: token, user_id: user_id)
    @token = token
    @user_id = user_id
  end

  def token
    @token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token, user_id: @user_id) do |o|
      o.sub_total = 0
      o.empty!
    end
  end

  def add_instrument(instrument_id)
    instrument = Instrument.find(instrument_id)
    instrument.in_cart!

    order.order_items.create(instrument_id: instrument_id, price: instrument.price)
    update_sub_total!
  end

  def destroy_item(order_item_id)
    item = order.order_items.find(order_item_id)
    if item
      item.destroy
      update_sub_total!
    end
  end

  private
  def update_sub_total!
    order.update_attributes!(sub_total: order.order_items.sum(:price))
  end

end



module SetCart
  def current_cart
    if user_signed_in?
       @current_cart ||= CurrentCart.new(token: cart_token, user_id: current_user.id)
    else
      flash.now[:alert] = "You are not signed in"
      redirect_to new_user_session_path
    end
  end

  def cart_token
    return session[:cart_token] if session[:cart_token]
    session[:cart_token] ||= SecureRandom.hex(8)
    return @cart_token = session[:cart_token]
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @instruments = Instrument.where(status: 'active').order("created_at desc")
  end

  def new
    @instrument = current_user.instruments.build
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

  def create
    @instrument = current_user.instruments.new(instrument_params)
    @instrument.active!
    if @instrument.save
      redirect_to root_path
    else
      redirect_to new_instruments_path
    end
  end

  def destroy
    @instrument = current_user.instruments.find(params[:id])
    if @instrument
      @instrument.destroy
    end
  end

  private
  def instrument_params
    p = params.require(:instrument).permit(:image, :brand, :model, :description, :condition, :finish, :price)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
    @order_items = current_cart.order.order_items
  end

  def create
    @order_item = current_cart.add_instrument(params[:instrument_id])
    redirect_to order_items_path
  end

  def destroy
    current_cart.destroy_item(params[:id])
    redirect_to order_items_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :current_cart

  def index
    @orders = current_user.orders.where.not(token: current_cart.token)
  end

  def checkout
    @order = current_cart.order
  end

  def create
    @order = current_cart.order
    if @order.update_attributes!(order_params.merge(status: 'open'))
      redirect_to root_path
      session[:cart_token] = nil
    else
      render "/new"
    end
  end

  def order_params
    params.require(:order).permit(:name, :adress)
  end

end

app/controllers/registrations_controller.rb
load "current_cart"
class RegistrationsController < Devise::RegistrationsController
  include SetCart

  protected

  def sign_up(_resource_name, user)
    super
    current_cart
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @current_sales = current_user.instruments.where(status: 'waiting')
  end

  def update
    instrument = current_user.instruments.find(params[:id])
      if instrument
        instrument.sold_out!
        redirect_to "/"
      end
  end

  def destroy
    instrument = current_user.instruments.find(params[:id])
    if instrument
      instrument.active!
      redirect_to "/"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  after_action :after_login, :only => :create

  private

  def after_login
    last = current_user.orders&.last
    if last
      if last.status == 'empty' || last.status == 'cart'
        session[:cart_token] = last.token
      end
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/instruments/index.html.haml
.card-columns
  - @instruments.each do |ins|
    .card
      .card-body.p-1
        - user = ins.user
        %i
          = "by #{user.name}"
          = gravatar_image_tag(user.email, alt: user.name, class: 'rounded-circle float-right')
        = image_tag ins.image.variant(resize: "400x400"), class: "d-block h-100 w-100"
        = link_to ins.brand + " " + ins.model, instrument_path(ins)
        %h5
          %br
            = number_to_currency(ins.price)
        %h6.mt-3
          = "Posted #{time_ago_in_words(ins.created_at)} ago"
        - if user == current_user
          %hr
            = link_to "Edit", edit_instrument_path(ins), class: "btn btn-outline-secondary mr-5 mt-5"
            = link_to "Delete", instruments_path(ins), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger ml-5 mt-5"

app/views/instruments/new.html.haml
= form_for @instrument do |f|
  .container
    .field
      = f.label :image
      = f.file_field :image
    .field
      = f.select :brand, options_for_select(Instrument::BRAND), prompt: "Select brand"
      = f.label :model
      = f.text_field :model
    .field
      = f.label :description
      = f.text_area :description
    .field
      = f.select :finish, options_for_select(Instrument::FINISH), prompt: "Select finish"
      = f.select :condition, options_for_select(Instrument::CONDITION), prompt: "Select condition"
    .field
      = f.label :price
      = f.text_field :price
    = f.submit "Create product"

app/views/instruments/show.html.haml
.row
  .col
    .card.w-40
      .card-body
        = image_tag @instrument.image, class: "block-center w-100"
        .card-title
          %br
            = "#{@instrument.brand} #{@instrument.model}"
        .card-text
          %table.table
            %tbody
              %tr
                %th.row Brand
                %td
                  = @instrument.brand
              %tr
                %th.row Model
                %td
                  = @instrument.model
              %tr
                %th.row Condition
                %td
                  = @instrument.condition
              %tr
                %th.row Finish
                %td
                  = @instrument.finish
          %p.ml-1
            = @instrument.description
          - if user_signed_in? && @instrument.user_id == current_user.id
            = link_to "Edit", edit_instrument_path(@instrument), class: "btn btn-light"
            = link_to "Delete", instrument_path(@instrument), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

  - if @instrument.status == 'active' && user_signed_in?
    .col
      .card
        .card-body
          = number_to_currency(@instrument.price)
          %hr
          = form_tag order_items_path do
            = hidden_field_tag :instrument_id, @instrument.id
            = submit_tag "Add to cart",  class: "btn btn-success"

app/views/order_items/index.html.haml
%h2 Current Cart
.row
  .col
    %table
      %thead
        %tr
          %td Instrument
          %td Price
          %td
      %tbody
        - @order_items.each do |item|
          %tr
            %td= link_to item.instrument.brand, instrument_path(item.instrument)
            %td= number_to_currency item.price
            %td
              = form_for item, method: :delete do |f|
                = f.submit "Remove", class: "btn btn-danger"
      %tfoot
        %tr
          %td( align="right")
            = number_to_currency current_cart.order.sub_total
        %tr
          %td( align="right")
            - if @order_items.count > 0
              = link_to "Checkout", checkout_path, class: "btn btn-primary"
  .col
    = link_to "History", history_path, class: "btn btn-info"

app/views/orders/_order.html.haml
.col
  %table
    %thead
      %tr
        %td Instrument
        %td Price
        %td
    %tbody
      - order.order_items.each do |item|

        %tr
          - instrument = item.instrument
          %td= link_to instrument.brand, instrument_path(instrument)
          %td= number_to_currency item.price

app/views/orders/checkout.html.haml
= form_for @order, url: checkout_path do |o|
  %br
    = o.label :name
  = o.text_field :name, value: @order.user.name
  %br
    = o.label :adress
  = o.text_field :adress
  %br
    = number_to_currency(@order.sub_total)
  = o.submit "Checkout", class: "btn btn-success"

app/views/orders/index.html.haml
- @orders.each do |order|
  .card.w-50
    .card-body
      = render 'orders/order', order: order

app/views/sales/index.html.haml
.card-columns
  - @current_sales.each do |ins|
    .card
      .card-body.p-1
        = image_tag ins.image.variant(resize: "400x400"), class: "d-block h-100 w-100"
        = link_to ins.brand + " " + ins.model, instrument_path(ins)
        %br
          = number_to_currency(ins.price)
        = link_to "Submit", sale_path(ins), method: :put, class: "btn btn-success mr-5 mt-5"
        = link_to "Decline", sale_path(ins), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger ml-5 mt-5"

app/views/stores/index.html.haml
%h1 Stores#index
%p Find me in app/views/stores/index.html.haml